### ISSUE TITLE
Interpretation tools

### ISSUE THREAD

**Issue by dfalbel** [mlverse/tabnet#12]

**Comment by skeydan** [comment]
hey, finally started looking at this - this is awesome!

While this issue is not implemented, I have a dumb question :-)
How can I access underlying model weights to manually calculate this
![image](https://user-images.githubusercontent.com/469371/102985031-cad8da00-450e-11eb-9343-ae2e207f75e4.png)

thanks!

**Comment by dfalbel** [comment]
the `nn_module` is a `network` slot. It depends on whether you used a workflow or not. But you can find it with `obj$fit$fit...$network` I don't know how many `fit`s you have to add :P

**Comment by skeydan** [comment]
thanks! In the meantime I've realized that -- if I understand correctly -- we need intermediate activations, not weights, and for the complete dataset ... (see code below)

Not sure how to accomplish this manually ... 
The Python repo you've been using as an example lets one pass callbacks into `fit` - could something like that be used to log those activations? (I haven't found any Python examples where they do this, - just speculating ...)

Thanks!

```
library(tabnet)
library(tidymodels)

split <- initial_split(iris, strata = Species)
train <- training(split)
test  <- testing(split)

rec <- recipe(Species ~ ., train)

model <- tabnet(epochs = 1, batch_size = 5) %>%
  set_engine("torch", verbose = TRUE) %>%
  set_mode("classification")

wf <- workflow() %>%
  add_model(model) %>%
  add_recipe(rec)

fit <- wf %>% fit(data = train)

# i think we would need to iterate over the acivations of all of these:
fit$fit$fit$fit$fit$network$tabnet$att_transformers
# for all instances of the dataset
```

**Comment by dfalbel** [comment]
We could refactor the `nn_module` to have a method that returns the activations. 
Something that would return right before this: https://github.com/mlverse/tabnet/blob/main/R/tab-network.R#L135 
or maybe just have an argument in `forward` that returns the activations if `TRUE`, do you think that would work?

**Comment by skeydan** [comment]
yeah - both sound great! Perhaps (1) makes most sense, because this would be a dedicated action you'd run once the model has been trained, on the whole dataset as opposed to a batch? 
(On the other hand - what if you want to know how that evolves over epochs? That would favor (2)...)

Just to be sure, what would you be returning? Is it this

https://github.com/mlverse/tabnet/blob/8e91020dccf10aa241d86c0fb7bb8c000044ac9a/R/tab-network.R#L114

or this

https://github.com/mlverse/tabnet/blob/8e91020dccf10aa241d86c0fb7bb8c000044ac9a/R/tab-network.R#L124

**Comment by dfalbel** [comment]
Actually, there is already this `forward_masks` method that seems to return what we want:

https://github.com/mlverse/tabnet/blob/main/R/tab-network.R#L139
