### ISSUE TITLE
(documentation) How to customize loss function?

### ISSUE THREAD

**Issue by comevussor** [mlverse/tabnet#152]
Thanks to all contributors for this package which is currently changing my life!

I'm doing multi-class classification and I can't find any documentation about how to customize the loss in tabnet. I want it to be the balanced accuracy. I tried the parameter `loss=yardstick::bal_accuracy_vec()` as a wild guess... and it failed. So, please could you complete the documentation to know how one can provide a specific loss function?

**Comment by cregouby** [comment]
Hello @comevussor 

Thank for the feedback on package usage, very appreciated.

Custom loss is supported as a function in {tabnet}

The good news is that you have an example in here : https://github.com/mlverse/tabnet/blob/3d3ce9925cc12a13adf9e7b2c2c9ebd57c7f3d5e/tests/testthat/test-hardhat_parameters.R#L211-L229

The bad news is that you must rely on {torch} loss, and you can not use {yardstick} metric as a loss. The reason is that the function must be differentiable to drive the gradient in the right direction...

There is plenty of loss functions in {torch}, all ending with `_loss`. If one is missing, you can also build yours as a torch module like `entmax` and `sparsemax` in https://github.com/mlverse/tabnet/blob/main/R/sparsemax.R

Hope it helps,

**Comment by comevussor** [comment]
Yes it does help, thank you. I 'll look into torch loss functions.
